<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="chassis_l" value="0.6" />
<xacro:property name="chassis_w" value="0.4" />
<xacro:property name="chassis_h" value="0.2" />
<xacro:property name="lidar_r" value="0.1" />
<xacro:property name="lidar_l" value="0.1" />
<xacro:property name="wheel_l" value="0.1" />
<xacro:property name="wheel_r" value="0.1" />

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>

    <material name="grey">
        <color rgba="0.8 0.8 0.8 1"/>
    </material>

    <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
    </material>

    <link name="base_footprint"/>

    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_l} ${chassis_w} ${chassis_h}"/>
            </geometry>
            <origin xyz="0 0 ${chassis_h/2}"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_l} ${chassis_w} ${chassis_h}"/>
            </geometry>
            <origin xyz="0 0 ${chassis_h/2}"/>
        </collision>
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_l}" radius="${wheel_r}"/>
            </geometry>
            <material name="grey"/>
            <origin rpy="1.57 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_l}" radius="${wheel_r}"/>
            </geometry>
            <origin rpy="1.57 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.3"/>
            <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
        </inertial>
    </link>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_l}" radius="${wheel_r}"/>
            </geometry>
            <material name="grey"/>
            <origin rpy="1.57 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_l}" radius="${wheel_r}"/>
            </geometry>
            <origin rpy="-1.57 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.3"/>
            <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
        </inertial>
    </link>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_r}"/>
            </geometry>
            <material name="black"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_r}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.002"/>
        </inertial>
    </link>

    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- JOINTS -->

    <joint name="chassis_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="chassis_link"/>
        <origin xyz="0.15 0 ${wheel_r}" rpy="0 0 0"/>
    </joint>

    <joint name="left_wheel_chassis_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="-0.15 0.2 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="right_wheel_chassis_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="-0.15 -0.2 0" rpy="3.14 0 0"/>
        <axis xyz="0 -1 0"/>
    </joint>

    <joint name="caster_wheel_chassis_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="0.15 0 0"/>
    </joint>

</robot>
