<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder length="${lidar_l}" radius="${lidar_r}"/>
            </geometry>
            <material name="red"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${lidar_l}" radius="${lidar_r}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <joint name="lidar_chassis_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.15 0 ${chassis_h+0.01}" rpy="0 0 0"/>
    </joint>        

    
    <gazebo reference="lidar_link">
    <sensor name="laser" type="gpu_lidar">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>100</update_rate>
        <gpu_lidar>
        <scan>
            <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
            </horizontal>
        </scan>
        <range>
            <min>0.3</min>
            <max>12</max>
            <resolution>0.01</resolution>
        </range>
        </gpu_lidar>
        <topic>scan</topic>
        <always_on>true</always_on>
        <enabled>true</enabled>
    </sensor>
    </gazebo>


    <plugin
      filename="ignition-gazebo-sensors-system"
      name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>


</robot>
