controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true


    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 1000.0
    base_frame_id: base_footprint

    left_wheel_names: ["left_wheel_chassis_joint"]
    right_wheel_names: ["right_wheel_chassis_joint"]

    wheel_separation: 0.40
    wheel_radius: 0.1

    use_stamped_vel: false
    enable_odom_tf: true



